### ISSUE TITLE
Project bundling

### ISSUE THREAD

**Issue by citymeterio** [fable-compiler/repl-legacy#42]
Hi,
I wanted to build fable/repl web from source.
I have little experience doing similar things.

Running start-app gave me following problems:
- globals.js (.net sdk ): solved just by removing this file
- complaining about babel-plugins: just copied it from Fable source code

Now I only have this left (cannot be found):
    
    <script src="js/repl/bundle.min.js"></script> 

I expect it to be from Fable source as well, but unfortunately I  cannot build anything from that project yet...
P

**Comment by alfonsogarciacaro** [comment]
Hi @citymeterio! Building the REPL is a bit of a complicated process because there're several repositories involved (although in principle running `sh build.sh WatchApp` or `build.cmd WatchApp` on Windows should work). The plan is to make it possible to componentize the REPL so it can be embedded in other webs, but we haven't cleaned up the build for this yet. Why do you want to build the REPL locally if I may ask?

**Comment by citymeterio** [comment]
Hi Alfonso!,
wow, what a pompt response :)

I am working on a personal project from the SmartCity/LivingCity/SmartCitizens/SmartGoverment realm using React, F#, TypeScript and wanted to incorporate Fable as well  (which may turn to be the main technology here)

I am creating a DSL language in F# for "smartcity problems" that will immidiately display visualizations (mainly maps so far) based on the algorithm created by the smart city domain expert or the plain city explorer/enthusiast.

To achieve that I want to send F# DSL code  from Monaco editor to Fable service and as a result do with the  SPA what I want (with React/Elmish style).

All of the sudden -  last weekend I saw a great awesome fabulous talk by Ewelina from FableConf and encountered FableRepl for the first time. It is exactly what I want to create/embed on my product so I started to play with it.

I have a solid .NET background but I am not well versed with other web stack yet - hence bulding even simpler project is a challenge.

I am about to create an "F# Advent" blog post about my project if you want to hear more details.

Taking into account your suggestion: I have following error (with Watch.App InstallYarn or Build.App):
1) System.Exception: Start of process c:\Users\longer\source\repos\fable-repl\repl\packages\Yarnpkg.js\tools\yarn.cmd failed. The system cannot find the file specified

I expect to be something with PATH on my computer although I have Yarn installed globally (used npm only for the time being)
 
Nevertheless I have to understand every piece of the code :)

**Comment by MangelMaxime** [comment]
@citymeterio You need to clone the `fable` repo at the same level as the `repl`

<img width="506" alt="capture d ecran 2018-11-06 a 09 14 45" src="https://user-images.githubusercontent.com/4760796/48051109-7e9e7480-e1a4-11e8-9ce4-47806e79e40c.png">

I need to reactivate the [`ensureRepoSetup`](https://github.com/fable-compiler/repl/blob/master/build.fsx#L86-L108) for `fable` repo too not that we use it again from the REPL repo.

**Comment by MangelMaxime** [comment]
Also you probably want to use [repl2](https://github.com/fable-compiler/repl2) instead of this repo.

**Comment by alfonsogarciacaro** [comment]
Actually, I just remembered you shouldn't need to clone the Fable repo because the build script is downloading the Fable bundle from Appveyor now. But @MangelMaxime is right, this is the old version of the repl. To prevent more confusions in the future, I will rename this repository to `repl-legacy` and repl2 will become `repl`. Gimme a couple of minutes.

BTW, your project sounds very interesting @citymeterio. I would be very happy if you could use the Fable repl with it, though it may be a bit challenging until we finish the work to componentize the repl.

I will close this issue now and will open a new one in the renamed repository.

**Comment by citymeterio** [comment]
Great, many thanks for your help gents!
I will play with it, learn, probably laverage the Repl-online for prototyping first.
Then I will try to help you tackle it from the wider perspective, it would be awesome to be the first/early consumer and contributor of Fable-Repl embeded component :)
